services:
  nginx:
    build: 
      context: ./.docker/nginx
      target: local
    container_name: pdf-api-local-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
      - ./.docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
      
    depends_on:
      - php-fpm

  php-fpm:
    build: ./.docker/php-fpm
    container_name: pdf-api-local-php
    environment:
      - DOCKER=local
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./app:/var/www/html
    links:
      - postgres

  postgres:
    container_name: pdf-api-local-postgres
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    container_name: pdf-api-local-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:      
