services:
  nginx:
    restart: always
    build: 
      context: ./.docker/nginx
      target: dev
    container_name: pdf-api-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
      - ./.docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/certbot/www/:/var/www/certbot/:ro      
    depends_on:
      - php-fpm
    #entrypoint: ["/usr/local/bin/entrypoint.sh"]
    #command: ["nginx", "-g", "daemon off;"]

  php-fpm:
    build: ./.docker/php-fpm
    container_name: pdf-api-php
    environment:
      - APP_ENV=dev
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
      - DB_HOST=pdf-api-postgres
      - DB_PORT=${POSTGRES_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASS}

    volumes:
      - ./app:/var/www/html
    # links:
    #   - postgres
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw    

  # postgres:
  #   container_name: pdf-api-postgres
  #   image: postgres:16.1
  #   restart: always
  #   environment:
  #     - DB_USER=${POSTGRES_USER}
  #     - DB_PASSWORD=${POSTGRES_PASS}
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  # adminer:
  #   container_name: pdf-api-php-adminer
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  pgdata:
